### ISSUE TITLE
Add more fields to grid queries

### ISSUE THREAD

**Issue by mauleyzaola** [mauleyzaola/biblio#8]
Add to the list these fields and allow to search into them as well:
author, book name, theme, tag

As discussed with @sergio-leyzaola

**Comment by mauleyzaola** [comment]
@sergio-leyzaola it is doable but in case one book has more than one author there will be repeated rows, one for each author. is that ok?

**Comment by sergio-leyzaola** [comment]
En la versión pasada, aparecían así cuando había varios autores de un
libro: "ASIMOV ISAAC/BOWKER RICHARD/FARBER JAMES/GARDNERMARTIN/GUNN
JAMES/KITTREDGE MARY/MARTIN GEORGE R. R./DOROTHY/SMITH" todos seguidos. Si
no puede ser así, entonces renglón para cada uno, que no es la mejor
opción, pero el tio quiere ver esa info completa en los listados.

On Mon, Aug 24, 2015 at 2:03 PM, Mauricio Leyzaola <notifications@github.com

**Comment by mauleyzaola** [comment]
this repo is visible for everyone, please write comments in english

will try to do like the old version if not possible then more rows
